name: AutoMessage
main: org.nevetime.autoMessage.AutoMessage
version: 1.0
api-version: 1.20
author: MihailPrud
description: Плагин на автоматические сообщения от студии NeveTime
depend: [PlaceholderAPI]

commands:
  broadcast:
    description: AutoMessage plugin commands
    usage: /automessage <reload|restart>
    permission: automessage.admin

permissions:
  automessage.admin:
    description: Allows managing the Broadcast plugin
    default: op
